#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'prod');

$composerAutoload = [
    __DIR__ . '/../vendor/autoload.php', // in yii2-dev repo
];
$vendorPath = null;
foreach ($composerAutoload as $autoload) {
    if (file_exists($autoload)) {
        require($autoload);
        $vendorPath = dirname($autoload);
        break;
    }
}


require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/../common/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/config/main.php'),
    require(__DIR__ . '/config/main-local.php')
);
$application = new yii\console\Application($config);
if (isset($vendorPath)) {
    $application->setVendorPath($vendorPath);
}
if (!isset($application->controllerMap['TimeTask'])) {
    $application->controllerMap['TimeTask'] = 'console\controllers\TimeTaskController';
}
if (!isset($application->controllerMap['ConfirmiOSPay'])) {
    $application->controllerMap['ConfirmiOSPay'] = 'console\controllers\ConfirmiOSPayController';
}
if (!isset($application->controllerMap['JPush'])) {
    $application->controllerMap['JPush'] = 'console\controllers\JPushController';
}
if (!isset($application->controllerMap['ConfirmAnswer'])) {
    $application->controllerMap['ConfirmAnswer'] = 'console\controllers\ConfirmAnswerController';
}
if (!isset($application->controllerMap['TeacherRating'])) {
    $application->controllerMap['TeacherRating'] = 'console\controllers\TeacherRatingController';
}
$exitCode = $application->run();
exit($exitCode);
